integers = set([-4, -3, -2, -1, 0, 1, 2, 3, 4])
natural_numbers = set([1, 2, 3, 4, 5, 6, 7, 8])
whole_numbers = set([0, 1, 2, 3, 4, 5, 6, 7, 8])

print( whole_numbers.union(natural_numbers) )
print( natural_numbers.union(whole_numbers) )
print( integers.intersection(whole_numbers) )
print( whole_numbers.update(set([7, 8 ,9])) )
print( natural_numbers.isdisjoint(integers) )
print( natural_numbers.issubset(whole_numbers) )
print( whole_numbers.issuperset(integers) )
print( natural_numbers.difference(whole_numbers) )
print( natural_numbers.symmetric_difference(whole_numbers) )
